export const list = [
  {
    id: "LH235",
    key: "Wood",
    p_width: "65cm",
    p_depth: "53cm",
    p_height: "185cm",
    c_width: "71cm",
    c_depth: "59cm",
    c_height: "192cm",
    c_volume: "0.80",
    price: '$1000',
    location: { lat: 37.7749, lng: -102.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Desk'
  },
  {
    id: "LH236",
    key: "Wood",
    p_width: "120cm",
    p_depth: "35cm",
    p_height: "89cm",
    c_width: "126cm",
    c_depth: "41cm",
    c_height: "96cm",
    c_volume: "0.50",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Table'
  },
  {
    id: "LH237",
    key: "Wood",
    p_width: "110cm",
    p_depth: "55cm",
    p_height: "165cm",
    c_width: "116cm",
    c_depth: "61cm",
    c_height: "172cm",
    c_volume: "1.22",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Table'
  },
  {
    id: "LH238",
    key: "Wood",
    p_width: "97cm",
    p_depth: "29cm",
    p_height: "89cm",
    c_width: "103cm",
    c_depth: "35cm",
    c_height: "96cm",
    c_volume: "0.35",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Table'
  },
  {
    id: "LH239",
    key: "Wood",
    p_width: "97cm",
    p_depth: "29cm",
    p_height: "89cm",
    c_width: "103cm",
    c_depth: "35cm",
    c_height: "96cm",
    c_volume: "0.35",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Table'
  },
  {
    id: "LH240",
    key: "Wood",
    p_width: "97cm",
    p_depth: "29cm",
    p_height: "89cm",
    c_width: "103cm",
    c_depth: "35cm",
    c_height: "96cm",
    c_volume: "0.35",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Table'
  },
  {
    id: "LH241",
    key: "Wood",
    p_width: "120cm",
    p_depth: "38cm",
    p_height: "110cm",
    c_width: "126cm",
    c_depth: "44cm",
    c_height: "117cm",
    c_volume: "0.65",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Table'
  },
  {
    id: "LH242",
    key: "Wood",
    p_width: "60cm",
    p_depth: "7cm",
    p_height: "80cm",
    c_width: "66cm",
    c_depth: "13cm",
    c_height: "87cm",
    c_volume: "0.07",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Table'
  },
  {
    id: "LH243",
    key: "Wood",
    p_width: "30cm",
    p_depth: "90cm",
    p_height: "180cm",
    c_width: "36cm",
    c_depth: "96cm",
    c_height: "187cm",
    c_volume: "0.65",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Chair'
  },
  {
    id: "LH244",
    key: "Wood",
    p_width: "156cm",
    p_depth: "41cm",
    p_height: "87cm",
    c_width: "162cm",
    c_depth: "47cm",
    c_height: "94cm",
    c_volume: "0.72",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Chair'
  },
  {
    id: "LH245",
    key: "Wood",
    p_width: "30cm",
    p_depth: "90cm",
    p_height: "180cm",
    c_width: "36cm",
    c_depth: "96cm",
    c_height: "187cm",
    c_volume: "0.65",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Chair'
  },
  {
    id: "LH246",
    key: "Wood",
    p_width: "98cm",
    p_depth: "55cm",
    p_height: "186cm",
    c_width: "104cm",
    c_depth: "61cm",
    c_height: "193cm",
    c_volume: "1.22",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Chair'
  },
  {
    id: "LH247",
    key: "Wood",
    p_width: "69cm",
    p_depth: "36cm",
    p_height: "168cm",
    c_width: "75cm",
    c_depth: "42cm",
    c_height: "175cm",
    c_volume: "0.55",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Chair'
  },
  {
    id: "LH248",
    key: "Wood",
    p_width: "96cm",
    p_depth: "38cm",
    p_height: "192cm",
    c_width: "102cm",
    c_depth: "44cm",
    c_height: "199cm",
    c_volume: "0.89",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Chair'
  },
  {
    id: "LH249",
    key: "Wood",
    p_width: "83cm",
    p_depth: "45cm",
    p_height: "160cm",
    c_width: "89cm",
    c_depth: "51cm",
    c_height: "167cm",
    c_volume: "0.76",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Chair'
  },
  {
    id: "LH250",
    key: "Wood",
    p_width: "85cm",
    p_depth: "45cm",
    p_height: "160cm",
    c_width: "91cm",
    c_depth: "51cm",
    c_height: "167cm",
    c_volume: "0.78",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Desk'
  },
  {
    id: "LH251",
    key: "Wood",
    p_width: "75cm",
    p_depth: "73cm",
    p_height: "190cm",
    c_width: "81cm",
    c_depth: "79cm",
    c_height: "197cm",
    c_volume: "1.26",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Desk'
  },
  {
    id: "LH252",
    key: "Wood",
    p_width: "78cm",
    p_depth: "40cm",
    p_height: "120cm",
    c_width: "84cm",
    c_depth: "46cm",
    c_height: "127cm",
    c_volume: "0.49",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Desk'
  },
  {
    id: "LH253",
    key: "Wood",
    p_width: "108cm",
    p_depth: "38cm",
    p_height: "138cm",
    c_width: "114cm",
    c_depth: "44cm",
    c_height: "144cm",
    c_volume: "0.73",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Desk'
  },
  {
    id: "LH254",
    key: "Wood",
    p_width: "80cm",
    p_depth: "40cm",
    p_height: "170cm",
    c_width: "86cm",
    c_depth: "46cm",
    c_height: "177cm",
    c_volume: "0.70",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Desk'
  },
  {
    id: "LH255",
    key: "Wood",
    p_width: "80cm",
    p_depth: "50cm",
    p_height: "35cm",
    c_width: "86cm",
    c_depth: "56cm",
    c_height: "42cm",
    c_volume: "0.20",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Desk'
  },
  {
    id: "LH256",
    key: "Wood",
    p_width: "153cm",
    p_depth: "45cm",
    p_height: "59cm",
    c_width: "159cm",
    c_depth: "51cm",
    c_height: "66cm",
    c_volume: "0.54",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Desk'
  },
  {
    id: "LH257",
    key: "Wood",
    p_width: "140cm",
    p_depth: "48cm",
    p_height: "73cm",
    c_width: "145cm",
    c_depth: "54cm",
    c_height: "80cm",
    c_volume: "0.63",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Desk'
  },
  {
    id: "LH258",
    key: "Wood",
    p_width: "90cm",
    p_depth: "35cm",
    p_height: "183cm",
    c_width: "96cm",
    c_depth: "41cm",
    c_height: "190cm",
    c_volume: "0.75",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Desk'
  },
  {
    id: "LH259",
    key: "Wood",
    p_width: "68cm",
    p_depth: "35cm",
    p_height: "172cm",
    c_width: "74cm",
    c_depth: "41cm",
    c_height: "179cm",
    c_volume: "0.54",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Wardrobe'
  },
  {
    id: "LH260",
    key: "Wood",
    p_width: "197cm",
    p_depth: "50cm",
    p_height: "52cm",
    c_width: "203cm",
    c_depth: "56cm",
    c_height: "59cm",
    c_volume: "0.67",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Wardrobe'
  },
  {
    id: "LH261",
    key: "Wood",
    p_width: "150cm",
    p_depth: "36cm",
    p_height: "89cm",
    c_width: "156cm",
    c_depth: "42cm",
    c_height: "96cm",
    c_volume: "0.63",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Wardrobe'
  },
  {
    id: "LH262",
    key: "Wood",
    p_width: "200cm",
    p_depth: "40cm",
    p_height: "90cm",
    c_width: "206cm",
    c_depth: "46cm",
    c_height: "97cm",
    c_volume: "0.92",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Wardrobe'
  },
  {
    id: "LH263",
    key: "Wood",
    p_width: "80cm",
    p_depth: "43cm",
    p_height: "90cm",
    c_width: "86cm",
    c_depth: "49cm",
    c_height: "97cm",
    c_volume: "0.41",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Wardrobe'
  },
  {
    id: "LH264",
    key: "Wood",
    p_width: "80cm",
    p_depth: "48cm",
    p_height: "171cm",
    c_width: "86cm",
    c_depth: "54cm",
    c_height: "178cm",
    c_volume: "0.83",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Wardrobe'
  },
  {
    id: "LH265",
    key: "Wood",
    p_width: "36cm",
    p_depth: "54cm",
    p_height: "72cm",
    c_width: "42cm",
    c_depth: "60cm",
    c_height: "79cm",
    c_volume: "0.20",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'FileBox'
  },
  {
    id: "LH266",
    key: "Wood",
    p_width: "41cm",
    p_depth: "76cm",
    p_height: "170cm",
    c_width: "47cm",
    c_depth: "82cm",
    c_height: "177cm",
    c_volume: "0.68",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'FileBox'
  },
  {
    id: "LH267",
    key: "Wood",
    p_width: "40cm",
    p_depth: "50cm",
    p_height: "150cm",
    c_width: "46cm",
    c_depth: "56cm",
    c_height: "157cm",
    c_volume: "0.40",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'FileBox'
  },
  {
    id: "LH268",
    key: "Wood",
    p_width: "98cm",
    p_depth: "57cm",
    p_height: "186cm",
    c_width: "104cm",
    c_depth: "61cm",
    c_height: "193cm",
    c_volume: "1.22",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'FileBox'
  },
  {
    id: "LH269",
    key: "Wood",
    p_width: "210cm",
    p_depth: "45cm",
    p_height: "112cm",
    c_width: "216cm",
    c_depth: "51cm",
    c_height: "119cm",
    c_volume: "1.31",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'FileBox'
  },
];
export const newList = [
  {
    id: "LH235",
    key: "Wood",
    p_width: "65cm",
    p_depth: "53cm",
    p_height: "185cm",
    c_width: "71cm",
    c_depth: "59cm",
    c_height: "192cm",
    c_volume: "0.80",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'FileBox'
  },
  {
    id: "LH236",
    key: "Wood",
    p_width: "120cm",
    p_depth: "35cm",
    p_height: "89cm",
    c_width: "126cm",
    c_depth: "41cm",
    c_height: "96cm",
    c_volume: "0.50",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'FileBox'
  },
  {
    id: "LH237",
    key: "Wood",
    p_width: "110cm",
    p_depth: "55cm",
    p_height: "165cm",
    c_width: "116cm",
    c_depth: "61cm",
    c_height: "172cm",
    c_volume: "1.22",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Fur'
  },
  {
    id: "LH238",
    key: "Wood",
    p_width: "97cm",
    p_depth: "29cm",
    p_height: "89cm",
    c_width: "103cm",
    c_depth: "35cm",
    c_height: "96cm",
    c_volume: "0.35",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Fur'
  },
  {
    id: "LH239",
    key: "Wood",
    p_width: "97cm",
    p_depth: "29cm",
    p_height: "89cm",
    c_width: "103cm",
    c_depth: "35cm",
    c_height: "96cm",
    c_volume: "0.35",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Fur'
  },
  {
    id: "LH240",
    key: "Wood",
    p_width: "97cm",
    p_depth: "29cm",
    p_height: "89cm",
    c_width: "103cm",
    c_depth: "35cm",
    c_height: "96cm",
    c_volume: "0.35",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Fur'
  },
  {
    id: "LH241",
    key: "Wood",
    p_width: "120cm",
    p_depth: "38cm",
    p_height: "110cm",
    c_width: "126cm",
    c_depth: "44cm",
    c_height: "117cm",
    c_volume: "0.65",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Fur'
  },
  {
    id: "LH242",
    key: "Wood",
    p_width: "60cm",
    p_depth: "7cm",
    p_height: "80cm",
    c_width: "66cm",
    c_depth: "13cm",
    c_height: "87cm",
    c_volume: "0.07",
    price: '$1000',
    location: { lat: 37.7749, lng: -122.4194 },
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque consequat dolor sed nulla facilisis, in congue erat vehicula.',
    type: 'Fur'
  }
];
